version: "2"

services:
  db:
    image: hope/mongodb:3.2
    container_name: db.ls
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/db:/data/db
    networks:
      - private

  auth:
    build: ./containers/auth
    container_name: auth.ls
    ports:
      - "3001:3000"
    networks:
      - private

  storage:
    build: ./containers/storage
    container_name: storage.ls
    ports:
      - "3002:3000"
    volumes:
      - ./volumes/storage:/data/storage
    networks:
      - private

networks:
  private:
    driver: bridge
