version: "2"

services:
  db:
    image: hope/mongodb:3.2
    container_name: db.ls
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/db:/data/db
    networks:
      - private

networks:
  private:
    driver: bridge
